### ISSUE TITLE
Incorrect use of modBy

### ISSUE THREAD

**Issue by cmditch** [prozacchiwawa/elm-urlbase64#7]
See https://github.com/prozacchiwawa/elm-urlbase64/pull/6 for fix

Also, happy to take over as maintainer of this if you wanna give me merge access. Thanks.

**Comment by cmditch** [comment]
Any chance we can make a release for #6 now that it's merged?

Thanks

**Comment by cmditch** [comment]
Thank you!

**Comment by prozacchiwawa** [comment]
apologies, was occupied by some other stuff.

**Comment by prozacchiwawa** [comment]
i have sent you an invite as well.  I apologies for not being as attentive
as one might be.
